language: go

go:
  - 1.6.2
  - tip

env:
    - GIMME_OS=linux GIMME_ARCH=amd64
    - GIMME_OS=darwin GIMME_ARCH=amd64
    - GIMME_OS=windows GIMME_ARCH=amd64

script:
    - make build

notifications:
  slack: miracloud:5r69ZAasA5mX50aig27LVKrs
